"""
Savage Worlds Core Rules — Hindrances
Source: Savage Worlds Adventure Edition
"""

SOURCE = "Core"

HINDRANCES = [
    # Major Hindrances
    {"name": "Arrogant", "severity": "Major",
     "summary": "Believes self superior; must humiliate foes"},
    {"name": "Bad Eyes", "severity": "Major",
     "summary": "-2 to all ranged attacks and Notice requiring sight beyond 5\""},
    {"name": "Blind", "severity": "Major",
     "summary": "-6 to all tasks requiring sight; -2 Parry"},
    {"name": "Bloodthirsty", "severity": "Major",
     "summary": "Never takes prisoners; -4 Charisma"},
    {"name": "Can't Swim", "severity": "Major",
     "summary": "-2 Athletics (swimming); drowns in 2d6 rounds if submerged"},
    {"name": "Clueless", "severity": "Major",
     "summary": "-1 Common Knowledge; often misses social cues"},
    {"name": "Code of Honor", "severity": "Major",
     "summary": "Keeps word; won't break personal ethics"},
    {"name": "Death Wish", "severity": "Major",
     "summary": "Wants to die accomplishing something; reckless"},
    {"name": "Delusional", "severity": "Major",
     "summary": "Believes something patently false"},
    {"name": "Doubting Thomas", "severity": "Major",
     "summary": "Refuses to believe in supernatural; -2 to fear/arcane knowledge"},
    {"name": "Elderly", "severity": "Major",
     "summary": "-1 Pace, Strength, Vigor die; +5 skill points"},
    {"name": "Enemy", "severity": "Major",
     "summary": "Powerful enemy seeks your destruction"},
    {"name": "Greedy", "severity": "Major",
     "summary": "Obsessed with wealth; steals/cheats for money"},
    {"name": "Habit", "severity": "Major",
     "summary": "Addicted to substance; Fatigue without it"},
    {"name": "Hard of Hearing", "severity": "Major",
     "summary": "Deaf; -6 to Notice hearing-based"},
    {"name": "Heroic", "severity": "Major",
     "summary": "Always helps those in need"},
    {"name": "Hesitant", "severity": "Major",
     "summary": "Draw two Action Cards, use lowest"},
    {"name": "Illiterate", "severity": "Major",
     "summary": "Cannot read or write"},
    {"name": "Lame", "severity": "Major",
     "summary": "-2 Pace; d4 running die"},
    {"name": "Loyal", "severity": "Major",
     "summary": "Never betrays friends; risks all for them"},
    {"name": "Mean", "severity": "Major",
     "summary": "-1 Persuasion; generally unpleasant"},
    {"name": "Mute", "severity": "Major",
     "summary": "Cannot speak"},
    {"name": "Obligation", "severity": "Major",
     "summary": "Owes significant time/resources to group or person"},
    {"name": "One Arm", "severity": "Major",
     "summary": "-4 to tasks requiring two arms"},
    {"name": "One Eye", "severity": "Major",
     "summary": "-2 ranged attacks and Notice if depth perception needed"},
    {"name": "Outsider", "severity": "Major",
     "summary": "-2 Persuasion with local culture; unfamiliar customs"},
    {"name": "Overconfident", "severity": "Major",
     "summary": "Believes can do anything; takes foolish risks"},
    {"name": "Pacifist", "severity": "Major",
     "summary": "Won't harm living beings"},
    {"name": "Phobia", "severity": "Major",
     "summary": "-2 to all Trait rolls in presence of fear; Panic possible"},
    {"name": "Poverty", "severity": "Major",
     "summary": "Half starting funds; can never keep money"},
    {"name": "Ruthless", "severity": "Major",
     "summary": "Will do anything to achieve goals"},
    {"name": "Secret", "severity": "Major",
     "summary": "Has dangerous secret; grave consequences if revealed"},
    {"name": "Slow", "severity": "Major",
     "summary": "-1 Pace; -2\" Running die"},
    {"name": "Small", "severity": "Major",
     "summary": "-1 Size; -1 Toughness"},
    {"name": "Stubborn", "severity": "Major",
     "summary": "Always wants own way; argues relentlessly"},
    {"name": "Tongue-Tied", "severity": "Major",
     "summary": "-1 Persuasion and Taunt; struggles with words"},
    {"name": "Ugly", "severity": "Major",
     "summary": "-2 Persuasion; notably unattractive"},
    {"name": "Vengeful", "severity": "Major",
     "summary": "Will pursue revenge at any cost"},
    {"name": "Vow", "severity": "Major",
     "summary": "Sworn to major cause; significant obligations"},
    {"name": "Wanted", "severity": "Major",
     "summary": "Authorities actively hunt you; serious crime"},
    {"name": "Yellow", "severity": "Major",
     "summary": "-2 to fear checks and resist Intimidation"},
    {"name": "Young", "severity": "Major",
     "summary": "-1 to 4 attribute points; only 10 skill points; +1 Benny per session"},
    
    # Minor Hindrances
    {"name": "All Thumbs", "severity": "Minor",
     "summary": "-2 to use mechanical/electronic devices"},
    {"name": "Anemic", "severity": "Minor",
     "summary": "-2 Vigor vs environmental effects (cold, heat, disease)"},
    {"name": "Bad Eyes", "severity": "Minor",
     "summary": "-1 to tasks requiring sight beyond 5\" without corrective lenses"},
    {"name": "Bad Luck", "severity": "Minor",
     "summary": "One less Benny per session"},
    {"name": "Big Mouth", "severity": "Minor",
     "summary": "Can't keep secrets; tells all"},
    {"name": "Cautious", "severity": "Minor",
     "summary": "Overly careful; slow to act"},
    {"name": "Clumsy", "severity": "Minor",
     "summary": "-2 Athletics and Stealth"},
    {"name": "Curious", "severity": "Minor",
     "summary": "Must investigate everything"},
    {"name": "Driven", "severity": "Minor",
     "summary": "Has personal goal that drives all actions"},
    {"name": "Enemy", "severity": "Minor",
     "summary": "Has enemy who seeks to harm you"},
    {"name": "Greedy", "severity": "Minor",
     "summary": "Always looking for more money"},
    {"name": "Habit", "severity": "Minor",
     "summary": "Annoying but not debilitating habit"},
    {"name": "Hard of Hearing", "severity": "Minor",
     "summary": "-4 to Notice hearing-based"},
    {"name": "Impulsive", "severity": "Minor",
     "summary": "Acts before thinking"},
    {"name": "Jealous", "severity": "Minor",
     "summary": "Envious of others' success"},
    {"name": "Loyal", "severity": "Minor",
     "summary": "Will not abandon friends"},
    {"name": "Mean", "severity": "Minor",
     "summary": "-1 Persuasion; unpleasant demeanor"},
    {"name": "Mild Mannered", "severity": "Minor",
     "summary": "-2 Intimidation"},
    {"name": "Obligation", "severity": "Minor",
     "summary": "Owes time/resources to group or person"},
    {"name": "Outsider", "severity": "Minor",
     "summary": "-2 Persuasion with local culture"},
    {"name": "Overconfident", "severity": "Minor",
     "summary": "Believes can handle any situation"},
    {"name": "Pacifist", "severity": "Minor",
     "summary": "Won't kill; fights to subdue"},
    {"name": "Phobia", "severity": "Minor",
     "summary": "-1 to all Trait rolls in presence of fear"},
    {"name": "Quirk", "severity": "Minor",
     "summary": "Has minor but noticeable eccentricity"},
    {"name": "Secret", "severity": "Minor",
     "summary": "Has secret that could cause embarrassment"},
    {"name": "Shamed", "severity": "Minor",
     "summary": "Lost honour; seeks redemption"},
    {"name": "Slow", "severity": "Minor",
     "summary": "-1 Pace"},
    {"name": "Stubborn", "severity": "Minor",
     "summary": "Argumentative about decisions"},
    {"name": "Suspicious", "severity": "Minor",
     "summary": "Distrusts others; -2 Persuasion"},
    {"name": "Thin Skinned", "severity": "Minor",
     "summary": "-4 vs social Tests and Taunt"},
    {"name": "Vengeful", "severity": "Minor",
     "summary": "Holds grudges; will get even eventually"},
    {"name": "Vow", "severity": "Minor",
     "summary": "Minor oath or restriction"},
    {"name": "Wanted", "severity": "Minor",
     "summary": "Someone hunts you; minor crime"},
]
