"""
Savage Worlds Core Rules — Powers
Source: Savage Worlds Adventure Edition
"""

SOURCE = "Core"

POWERS = [
    # Damage Powers
    {"name": "Bolt", "rank": "Novice", "pp": "1", "range": "Smarts×2", "duration": "Instant",
     "summary": "Single target 2d6 damage; 2 PP for 3d6 with Raise"},
    {"name": "Blast", "rank": "Seasoned", "pp": "3", "range": "Smarts×2", "duration": "Instant",
     "summary": "Medium Burst Template, 2d6 damage; 3d6 on Raise"},
    {"name": "Burst", "rank": "Novice", "pp": "2", "range": "Cone Template", "duration": "Instant",
     "summary": "Cone Template, 2d6 damage; 3d6 on Raise"},
    {"name": "Smite", "rank": "Novice", "pp": "2", "range": "Touch", "duration": "5 rounds",
     "summary": "Weapon gains +2 damage; +4 on Raise"},
    {"name": "Damage Field", "rank": "Seasoned", "pp": "4", "range": "Touch", "duration": "5 rounds",
     "summary": "2d4 damage to adjacent attackers; 2d6 on Raise"},
    
    # Utility Powers
    {"name": "Arcane Protection", "rank": "Novice", "pp": "1", "range": "Touch", "duration": "5 rounds",
     "summary": "+2 to resist powers and +2 armor vs damage powers; +4 on Raise"},
    {"name": "Barrier", "rank": "Seasoned", "pp": "2/section", "range": "Smarts", "duration": "5 rounds",
     "summary": "Create wall; Hardness 10"},
    {"name": "Boost/Lower Trait", "rank": "Novice", "pp": "2", "range": "Smarts", "duration": "5 rounds",
     "summary": "Raise/lower one Trait die type; 2 types on Raise"},
    {"name": "Burrow", "rank": "Novice", "pp": "2", "range": "Touch", "duration": "5 rounds",
     "summary": "Move through earth at half Pace"},
    {"name": "Deflection", "rank": "Novice", "pp": "2", "range": "Touch", "duration": "5 rounds",
     "summary": "-2 to attacks vs target; -4 on Raise"},
    {"name": "Detect/Conceal Arcana", "rank": "Novice", "pp": "2", "range": "Smarts", "duration": "5 rounds",
     "summary": "Detect or hide magical items and effects"},
    {"name": "Disguise", "rank": "Seasoned", "pp": "2", "range": "Touch", "duration": "10 min",
     "summary": "Change appearance; +2 Notice to see through on Raise"},
    {"name": "Dispel", "rank": "Seasoned", "pp": "1", "range": "Smarts", "duration": "Instant",
     "summary": "Opposed roll to end power; automatic on Raise"},
    {"name": "Elemental Manipulation", "rank": "Novice", "pp": "1", "range": "Smarts", "duration": "5 rounds",
     "summary": "Minor control over element (1 cubic yard)"},
    {"name": "Empathy", "rank": "Novice", "pp": "1", "range": "Smarts", "duration": "5 rounds",
     "summary": "+1 social rolls; +2 on Raise"},
    {"name": "Entangle", "rank": "Novice", "pp": "2", "range": "Smarts", "duration": "Instant",
     "summary": "Restrain target; Bound on Raise"},
    {"name": "Environmental Protection", "rank": "Novice", "pp": "2", "range": "Touch", "duration": "1 hour",
     "summary": "Protection from one environmental hazard"},
    {"name": "Farsight", "rank": "Seasoned", "pp": "2", "range": "Smarts", "duration": "5 rounds",
     "summary": "See at distance; ignore 2 points Range penalties"},
    {"name": "Fear", "rank": "Novice", "pp": "2", "range": "Smarts×2", "duration": "Instant",
     "summary": "Spirit roll or Panicked; Shaken on success"},
    {"name": "Fly", "rank": "Veteran", "pp": "3", "range": "Touch", "duration": "5 rounds",
     "summary": "Fly at Pace 12"},
    {"name": "Growth/Shrink", "rank": "Seasoned", "pp": "2/Size", "range": "Smarts", "duration": "5 rounds",
     "summary": "Increase/decrease Size up to 4 levels"},
    {"name": "Havoc", "rank": "Seasoned", "pp": "2", "range": "Smarts", "duration": "Instant",
     "summary": "Move targets in MBT; Str roll or fall prone"},
    {"name": "Healing", "rank": "Novice", "pp": "3", "range": "Touch", "duration": "Instant",
     "summary": "Remove 1 Wound; 2 Wounds on Raise (within Golden Hour)"},
    {"name": "Illusion", "rank": "Novice", "pp": "3", "range": "Smarts", "duration": "5 rounds",
     "summary": "Create visual illusion; Notice to disbelieve"},
    {"name": "Intangibility", "rank": "Veteran", "pp": "5", "range": "Touch", "duration": "5 rounds",
     "summary": "Pass through solid matter"},
    {"name": "Invisibility", "rank": "Seasoned", "pp": "5", "range": "Touch", "duration": "5 rounds",
     "summary": "Target invisible; -4/-6 to hit"},
    {"name": "Light/Darkness", "rank": "Novice", "pp": "2", "range": "Smarts", "duration": "10 min",
     "summary": "Create or negate light in LBT"},
    {"name": "Mind Link", "rank": "Novice", "pp": "1", "range": "Smarts", "duration": "30 min",
     "summary": "Telepathic communication"},
    {"name": "Mind Reading", "rank": "Novice", "pp": "2", "range": "Smarts", "duration": "1 round",
     "summary": "Opposed Spirit; read surface thoughts"},
    {"name": "Mind Wipe", "rank": "Veteran", "pp": "3", "range": "Smarts", "duration": "Instant",
     "summary": "Remove up to 1 hour of memory; 1 day on Raise"},
    {"name": "Object Reading", "rank": "Novice", "pp": "2", "range": "Touch", "duration": "Instant",
     "summary": "Sense last owner's identity and emotions"},
    {"name": "Protection", "rank": "Novice", "pp": "1", "range": "Touch", "duration": "5 rounds",
     "summary": "+2 Armor; +4 on Raise"},
    {"name": "Puppet", "rank": "Veteran", "pp": "3", "range": "Smarts", "duration": "5 rounds",
     "summary": "Opposed Spirit; control actions"},
    {"name": "Relief", "rank": "Novice", "pp": "1", "range": "Touch", "duration": "Instant",
     "summary": "Remove 1 Fatigue; Shaken/Stunned on Raise"},
    {"name": "Resurrection", "rank": "Heroic", "pp": "30", "range": "Touch", "duration": "Instant",
     "summary": "Return recently dead to life"},
    {"name": "Shape Change", "rank": "Special", "pp": "3+", "range": "Self", "duration": "5 rounds",
     "summary": "Transform into animal; cost varies by Size"},
    {"name": "Sloth/Speed", "rank": "Novice", "pp": "2", "range": "Smarts", "duration": "5 rounds",
     "summary": "Halve or double target's Pace"},
    {"name": "Slumber", "rank": "Seasoned", "pp": "2", "range": "Smarts", "duration": "1 hour",
     "summary": "Target falls asleep; Spirit to resist"},
    {"name": "Speak Language", "rank": "Novice", "pp": "1", "range": "Touch", "duration": "10 min",
     "summary": "Speak any language"},
    {"name": "Stun", "rank": "Novice", "pp": "2", "range": "Smarts", "duration": "Instant",
     "summary": "Vigor roll or Stunned; Shaken on success"},
    {"name": "Summon Ally", "rank": "Novice", "pp": "2+", "range": "Smarts", "duration": "5 rounds",
     "summary": "Summon creature; cost by Size"},
    {"name": "Telekinesis", "rank": "Seasoned", "pp": "3", "range": "Smarts×2", "duration": "5 rounds",
     "summary": "Move objects with Spirit die × 10 lbs"},
    {"name": "Teleport", "rank": "Seasoned", "pp": "2", "range": "Smarts", "duration": "Instant",
     "summary": "Teleport up to 12\"; 24\" on Raise"},
    {"name": "Wall Walker", "rank": "Novice", "pp": "2", "range": "Touch", "duration": "5 rounds",
     "summary": "Walk on walls/ceilings at normal Pace"},
    {"name": "Warrior's Gift", "rank": "Seasoned", "pp": "4", "range": "Touch", "duration": "5 rounds",
     "summary": "Grant one Combat Edge"},
    {"name": "Zombie", "rank": "Veteran", "pp": "3/corpse", "range": "Touch", "duration": "1 hour",
     "summary": "Animate corpse as zombie servant"},
]
