"""
Savage Worlds Core Rules — Edges
Source: Savage Worlds Adventure Edition
"""

SOURCE = "Core"

EDGES = [
    # Background Edges
    {"name": "Alertness", "rank": "Novice", "type": "Background",
     "requirements": "", "summary": "+2 Notice"},
    {"name": "Ambidextrous", "rank": "Novice", "type": "Background",
     "requirements": "Agility d8+", "summary": "Ignore -2 off-hand penalty"},
    {"name": "Arcane Background", "rank": "Novice", "type": "Background",
     "requirements": "Special", "summary": "Allows access to supernatural powers"},
    {"name": "Arcane Resistance", "rank": "Novice", "type": "Background",
     "requirements": "Spirit d8+", "summary": "+2 to resist powers; +2 armor vs damage powers"},
    {"name": "Aristocrat", "rank": "Novice", "type": "Background",
     "requirements": "", "summary": "+2 Common Knowledge (high society); +2 Persuasion (nobility)"},
    {"name": "Attractive", "rank": "Novice", "type": "Background",
     "requirements": "Vigor d6+", "summary": "+1 Performance and Persuasion"},
    {"name": "Berserk", "rank": "Novice", "type": "Background",
     "requirements": "", "summary": "+1 melee damage/Toughness; ignore Wound penalties; -2 Parry"},
    {"name": "Brave", "rank": "Novice", "type": "Background",
     "requirements": "Spirit d6+", "summary": "+2 to Fear checks"},
    {"name": "Brawny", "rank": "Novice", "type": "Background",
     "requirements": "Strength d6+, Vigor d6+", "summary": "+1 Size (Toughness); +1 Strength die for encumbrance"},
    {"name": "Brute", "rank": "Novice", "type": "Background",
     "requirements": "Strength d6+, Vigor d6+", "summary": "Link Athletics to Strength; +1 damage in melee"},
    {"name": "Charismatic", "rank": "Novice", "type": "Background",
     "requirements": "Spirit d8+", "summary": "+2 Persuasion; reroll critical failure"},
    {"name": "Elan", "rank": "Novice", "type": "Background",
     "requirements": "Spirit d8+", "summary": "+2 when spending Benny on Trait roll"},
    {"name": "Fame", "rank": "Novice", "type": "Background",
     "requirements": "", "summary": "+1 Persuasion; +10% income"},
    {"name": "Fast Healer", "rank": "Novice", "type": "Background",
     "requirements": "Vigor d8+", "summary": "+2 natural healing; check every 3 days"},
    {"name": "Fleet-Footed", "rank": "Novice", "type": "Background",
     "requirements": "Agility d6+", "summary": "+2 Pace; d10 running die"},
    {"name": "Linguist", "rank": "Novice", "type": "Background",
     "requirements": "Smarts d6+", "summary": "+1 language per Smarts die"},
    {"name": "Luck", "rank": "Novice", "type": "Background",
     "requirements": "", "summary": "+1 Benny per session"},
    {"name": "Quick", "rank": "Novice", "type": "Background",
     "requirements": "Agility d8+", "summary": "Redraw Action Cards 5 or lower"},
    {"name": "Rich", "rank": "Novice", "type": "Background",
     "requirements": "", "summary": "3× starting funds; $150K annual salary"},
    
    # Combat Edges
    {"name": "Block", "rank": "Seasoned", "type": "Combat",
     "requirements": "Fighting d8+", "summary": "+1 Parry; ignore 1 Gang Up bonus"},
    {"name": "Brawler", "rank": "Novice", "type": "Combat",
     "requirements": "Strength d8+, Vigor d8+", "summary": "+1 Toughness; +1 unarmed damage"},
    {"name": "Calculating", "rank": "Novice", "type": "Combat",
     "requirements": "Smarts d8+", "summary": "Ignore 2 points of penalties on Action Card 5+"},
    {"name": "Combat Reflexes", "rank": "Seasoned", "type": "Combat",
     "requirements": "", "summary": "+2 Spirit to recover from Shaken or Stunned"},
    {"name": "Counterattack", "rank": "Seasoned", "type": "Combat",
     "requirements": "Fighting d8+", "summary": "Free attack at -2 when foe fails Fighting"},
    {"name": "Dead Shot", "rank": "Seasoned", "type": "Combat",
     "requirements": "Athletics or Shooting d8+", "summary": "Double damage on first Joker attack"},
    {"name": "Dodge", "rank": "Seasoned", "type": "Combat",
     "requirements": "Agility d8+", "summary": "-2 to hit with ranged attacks"},
    {"name": "Double Tap", "rank": "Seasoned", "type": "Combat",
     "requirements": "Shooting d6+", "summary": "+1 damage when firing 2 rounds"},
    {"name": "Extraction", "rank": "Novice", "type": "Combat",
     "requirements": "Agility d8+", "summary": "One adjacent foe doesn't get free attack"},
    {"name": "Feint", "rank": "Novice", "type": "Combat",
     "requirements": "Fighting d8+", "summary": "Fighting vs Smarts to ignore Shield/Parry"},
    {"name": "First Strike", "rank": "Novice", "type": "Combat",
     "requirements": "Agility d8+", "summary": "Free attack vs foe who moves adjacent"},
    {"name": "Free Runner", "rank": "Novice", "type": "Combat",
     "requirements": "Agility d8+, Athletics d6+", "summary": "Ignore Difficult Ground; +2 Athletics (climbing, jumping)"},
    {"name": "Frenzy", "rank": "Seasoned", "type": "Combat",
     "requirements": "Fighting d8+", "summary": "Extra Fighting attack at -2"},
    {"name": "Giant Killer", "rank": "Veteran", "type": "Combat",
     "requirements": "", "summary": "+1d6 damage vs Size +2 or larger"},
    {"name": "Hard to Kill", "rank": "Novice", "type": "Combat",
     "requirements": "Spirit d8+", "summary": "Ignore Wound penalties to Vigor when Incapacitated"},
    {"name": "Improvisational Fighter", "rank": "Seasoned", "type": "Combat",
     "requirements": "Smarts d6+", "summary": "Ignore -2 improvised weapon penalty"},
    {"name": "Iron Jaw", "rank": "Novice", "type": "Combat",
     "requirements": "Vigor d8+", "summary": "+2 Soak; +2 Vigor vs knockout"},
    {"name": "Killer Instinct", "rank": "Seasoned", "type": "Combat",
     "requirements": "", "summary": "Win ties on opposed rolls"},
    {"name": "Level Headed", "rank": "Seasoned", "type": "Combat",
     "requirements": "Smarts d8+", "summary": "Draw additional Action Card, act on best"},
    {"name": "Marksman", "rank": "Seasoned", "type": "Combat",
     "requirements": "Athletics or Shooting d8+", "summary": "+1 ranged attacks if no movement"},
    {"name": "Martial Artist", "rank": "Novice", "type": "Combat",
     "requirements": "Fighting d6+", "summary": "Unarmed damage is Str+d4; always armed"},
    {"name": "Mighty Blow", "rank": "Seasoned", "type": "Combat",
     "requirements": "Fighting d8+", "summary": "Double melee damage on first Joker attack"},
    {"name": "Nerves of Steel", "rank": "Novice", "type": "Combat",
     "requirements": "Vigor d8+", "summary": "Ignore 1 Wound penalty"},
    {"name": "No Mercy", "rank": "Seasoned", "type": "Combat",
     "requirements": "", "summary": "+2 damage when spending Benny"},
    {"name": "Rapid Fire", "rank": "Seasoned", "type": "Combat",
     "requirements": "Shooting d6+", "summary": "Extra Shooting attack at -2"},
    {"name": "Rock and Roll", "rank": "Seasoned", "type": "Combat",
     "requirements": "Shooting d8+", "summary": "Ignore recoil penalty with automatic fire"},
    {"name": "Steady Hands", "rank": "Novice", "type": "Combat",
     "requirements": "Agility d8+", "summary": "Ignore Unstable Platform; -1 running penalty"},
    {"name": "Sweep", "rank": "Novice", "type": "Combat",
     "requirements": "Strength d8+, Fighting d8+", "summary": "Attack all adjacent foes at -2"},
    {"name": "Trademark Weapon", "rank": "Novice", "type": "Combat",
     "requirements": "d8+ in related skill", "summary": "+1 to attacks with specific weapon"},
    {"name": "Two-Fisted", "rank": "Novice", "type": "Combat",
     "requirements": "Agility d8+", "summary": "Make extra Fighting attack with second weapon"},
    {"name": "Two-Gun Kid", "rank": "Novice", "type": "Combat",
     "requirements": "Agility d8+", "summary": "Make extra Shooting attack with second weapon"},
    
    # Leadership Edges
    {"name": "Command", "rank": "Novice", "type": "Leadership",
     "requirements": "Smarts d6+", "summary": "+1 to recover from Shaken/Stunned for troops in Command Range"},
    {"name": "Command Presence", "rank": "Seasoned", "type": "Leadership",
     "requirements": "Command", "summary": "Increase Command Range to 10\""},
    {"name": "Fervor", "rank": "Veteran", "type": "Leadership",
     "requirements": "Spirit d8+, Command", "summary": "+1 melee damage for troops in Command Range"},
    {"name": "Hold the Line!", "rank": "Seasoned", "type": "Leadership",
     "requirements": "Smarts d8+, Command", "summary": "+1 Toughness for troops in Command Range"},
    {"name": "Inspire", "rank": "Seasoned", "type": "Leadership",
     "requirements": "Command", "summary": "+1 to one Trait for troops in Command Range"},
    {"name": "Natural Leader", "rank": "Novice", "type": "Leadership",
     "requirements": "Spirit d8+, Command", "summary": "Leadership Edges affect Wild Cards"},
    {"name": "Tactician", "rank": "Seasoned", "type": "Leadership",
     "requirements": "Smarts d8+, Command, Battle d6+", "summary": "+1 Action Card per Rank for allies"},
    
    # Power Edges
    {"name": "Artificer", "rank": "Seasoned", "type": "Power",
     "requirements": "AB", "summary": "Create temporary magical devices"},
    {"name": "Channeling", "rank": "Seasoned", "type": "Power",
     "requirements": "AB", "summary": "-1 PP cost on Raise"},
    {"name": "Concentration", "rank": "Seasoned", "type": "Power",
     "requirements": "AB", "summary": "Double Duration when maintaining single power"},
    {"name": "Extra Effort", "rank": "Seasoned", "type": "Power",
     "requirements": "AB, Focus/Faith/Spellcasting d6+", "summary": "+1 damage/effect per 2 PP"},
    {"name": "Mentalist", "rank": "Novice", "type": "Power",
     "requirements": "AB (Psionics)", "summary": "+2 to opposed Psionics rolls"},
    {"name": "New Powers", "rank": "Novice", "type": "Power",
     "requirements": "AB", "summary": "+2 new powers"},
    {"name": "Power Points", "rank": "Novice", "type": "Power",
     "requirements": "AB", "summary": "+5 Power Points"},
    {"name": "Power Surge", "rank": "Seasoned", "type": "Power",
     "requirements": "AB, arcane skill d8+", "summary": "+2 PP when dealt Joker"},
    {"name": "Rapid Recharge", "rank": "Seasoned", "type": "Power",
     "requirements": "Spirit d6+, AB", "summary": "Recover 10 PP/hour"},
    {"name": "Soul Drain", "rank": "Seasoned", "type": "Power",
     "requirements": "AB", "summary": "Recover PP with Vigor roll; 1 Wound on failure"},
    {"name": "Wizard", "rank": "Novice", "type": "Power",
     "requirements": "AB (Magic)", "summary": "Swap powers with 10 minutes and arcane skill roll"},
    
    # Professional Edges
    {"name": "Ace", "rank": "Novice", "type": "Professional",
     "requirements": "Agility d8+", "summary": "+2 to Boating, Driving, Piloting; may Soak vehicle damage"},
    {"name": "Acrobat", "rank": "Novice", "type": "Professional",
     "requirements": "Agility d8+, Athletics d8+", "summary": "+2 Agility-based actions; +1 Parry if no encumbrance"},
    {"name": "Combat Medic", "rank": "Seasoned", "type": "Professional",
     "requirements": "Healing d6+", "summary": "Don't cause Wounds on Healing failure"},
    {"name": "Healer", "rank": "Novice", "type": "Professional",
     "requirements": "Spirit d8+", "summary": "+2 Healing"},
    {"name": "Investigator", "rank": "Novice", "type": "Professional",
     "requirements": "Smarts d8+, Research d8+", "summary": "+2 Research and Notice (searching)"},
    {"name": "Jack-of-All-Trades", "rank": "Novice", "type": "Professional",
     "requirements": "Smarts d10+", "summary": "Attempt any skill at d4"},
    {"name": "McGyver", "rank": "Novice", "type": "Professional",
     "requirements": "Smarts d6+, Repair d6+", "summary": "Create gadgets from common items"},
    {"name": "Mr. Fix It", "rank": "Novice", "type": "Professional",
     "requirements": "Repair d8+", "summary": "+2 Repair; halve time"},
    {"name": "Scholar", "rank": "Novice", "type": "Professional",
     "requirements": "Research d8+", "summary": "+2 to two knowledge skills"},
    {"name": "Soldier", "rank": "Novice", "type": "Professional",
     "requirements": "Strength d6+, Vigor d6+", "summary": "+2 Vigor to resist environment; strength one die higher for encumbrance"},
    {"name": "Thief", "rank": "Novice", "type": "Professional",
     "requirements": "Agility d8+, Stealth d6+, Thievery d6+", "summary": "+1 Thievery; +1 Stealth in urban"},
    {"name": "Woodsman", "rank": "Novice", "type": "Professional",
     "requirements": "Spirit d6+, Survival d8+", "summary": "+2 Survival and Stealth (wilds)"},
    
    # Social Edges
    {"name": "Bolster", "rank": "Novice", "type": "Social",
     "requirements": "Spirit d8+", "summary": "Raise removes Shaken/Stunned from allies"},
    {"name": "Common Bond", "rank": "Novice", "type": "Social",
     "requirements": "Spirit d8+", "summary": "Give Bennies to allies"},
    {"name": "Connections", "rank": "Novice", "type": "Social",
     "requirements": "", "summary": "Call in favours from organization"},
    {"name": "Humiliate", "rank": "Seasoned", "type": "Social",
     "requirements": "Taunt d8+", "summary": "Shaken victims take -1 to all rolls until they recover"},
    {"name": "Menacing", "rank": "Novice", "type": "Social",
     "requirements": "", "summary": "+2 Intimidation"},
    {"name": "Provoke", "rank": "Novice", "type": "Social",
     "requirements": "Taunt d6+", "summary": "Test forces opponent to attack you"},
    {"name": "Rabble-Rouser", "rank": "Seasoned", "type": "Social",
     "requirements": "Spirit d8+", "summary": "Taunt all foes within 6\" with single action"},
    {"name": "Reliable", "rank": "Novice", "type": "Social",
     "requirements": "Spirit d8+", "summary": "+1 to Support rolls; +2 on Raise"},
    {"name": "Retort", "rank": "Novice", "type": "Social",
     "requirements": "Taunt d6+", "summary": "Free Taunt if foe fails Taunt vs you"},
    {"name": "Streetwise", "rank": "Novice", "type": "Social",
     "requirements": "Smarts d6+", "summary": "+2 Common Knowledge and Notice (urban)"},
    {"name": "Strong Willed", "rank": "Novice", "type": "Social",
     "requirements": "Spirit d8+", "summary": "+2 vs social Tests and Smarts/Spirit resist"},
    {"name": "Work the Room", "rank": "Novice", "type": "Social",
     "requirements": "Spirit d8+", "summary": "Reroll Support on Persuasion"},
    {"name": "Work the Crowd", "rank": "Seasoned", "type": "Social",
     "requirements": "Work the Room", "summary": "Test up to 5 targets within 6\""},
    
    # Weird Edges
    {"name": "Beast Bond", "rank": "Novice", "type": "Weird",
     "requirements": "", "summary": "Animal companion is Wild Card"},
    {"name": "Beast Master", "rank": "Novice", "type": "Weird",
     "requirements": "Spirit d8+", "summary": "Gain animal companion"},
    {"name": "Champion", "rank": "Novice", "type": "Weird",
     "requirements": "Spirit d8+, Fighting d6+", "summary": "+2 damage and Toughness vs supernatural evil"},
    {"name": "Chi", "rank": "Veteran", "type": "Weird",
     "requirements": "AB (Gifted)", "summary": "Once per encounter, reroll failed arcane skill roll"},
    {"name": "Danger Sense", "rank": "Novice", "type": "Weird",
     "requirements": "", "summary": "Notice at -2 to detect danger; can't be Surprised"},
    {"name": "Healer", "rank": "Novice", "type": "Weird",
     "requirements": "Spirit d8+", "summary": "+2 Healing"},
    {"name": "Holy/Unholy Warrior", "rank": "Novice", "type": "Weird",
     "requirements": "Spirit d8+, AB (Miracles)", "summary": "+2 damage vs supernatural evil; Smite at +2"},
    {"name": "Scavenger", "rank": "Novice", "type": "Weird",
     "requirements": "Luck", "summary": "Once per encounter, find useful item"},
    
    # Legendary Edges
    {"name": "Followers", "rank": "Legendary", "type": "Legendary",
     "requirements": "", "summary": "Gain 5 loyal followers"},
    {"name": "Professional", "rank": "Legendary", "type": "Legendary",
     "requirements": "d12+ in any Trait", "summary": "Chosen Trait becomes d12+1"},
    {"name": "Sidekick", "rank": "Legendary", "type": "Legendary",
     "requirements": "", "summary": "Gain Wild Card companion"},
    {"name": "Tough as Nails", "rank": "Legendary", "type": "Legendary",
     "requirements": "Vigor d8+", "summary": "+1 Toughness; +1 Wound threshold"},
    {"name": "Weapon Master", "rank": "Legendary", "type": "Legendary",
     "requirements": "Fighting d12+", "summary": "+1 Parry; +2 damage with melee weapons"},
]
