"""
Savage Worlds Core Rules — Weapons, Armour, and Gear
Source: Savage Worlds Adventure Edition
"""

SOURCE = "Core"

WEAPONS = [
    # Melee Weapons
    {"name": "Unarmed", "damage_str": "Str", "ap": 0, "trait_type": "Melee",
     "range": "", "reach": 0, "weight": 0, "cost": "0", "notes": ""},
    {"name": "Dagger/Knife", "damage_str": "Str+d4", "ap": 0, "trait_type": "Melee",
     "range": "3/6/12", "reach": 0, "weight": 1, "cost": "25", "notes": "Can be thrown"},
    {"name": "Short Sword", "damage_str": "Str+d6", "ap": 0, "trait_type": "Melee",
     "range": "", "reach": 0, "weight": 2, "cost": "100", "notes": ""},
    {"name": "Long Sword", "damage_str": "Str+d8", "ap": 0, "trait_type": "Melee",
     "range": "", "reach": 0, "weight": 3, "cost": "300", "notes": ""},
    {"name": "Great Sword", "damage_str": "Str+d10", "ap": 0, "trait_type": "Melee",
     "range": "", "reach": 0, "weight": 6, "cost": "400", "notes": "Two hands"},
    {"name": "Rapier", "damage_str": "Str+d4", "ap": 0, "trait_type": "Melee",
     "range": "", "reach": 0, "weight": 2, "cost": "150", "notes": "Parry +1"},
    {"name": "Axe", "damage_str": "Str+d6", "ap": 0, "trait_type": "Melee",
     "range": "3/6/12", "reach": 0, "weight": 2, "cost": "100", "notes": "Can be thrown"},
    {"name": "Battle Axe", "damage_str": "Str+d8", "ap": 0, "trait_type": "Melee",
     "range": "", "reach": 0, "weight": 4, "cost": "300", "notes": ""},
    {"name": "Great Axe", "damage_str": "Str+d10", "ap": 0, "trait_type": "Melee",
     "range": "", "reach": 0, "weight": 7, "cost": "400", "notes": "AP 1, Two hands"},
    {"name": "Mace", "damage_str": "Str+d6", "ap": 0, "trait_type": "Melee",
     "range": "", "reach": 0, "weight": 4, "cost": "100", "notes": ""},
    {"name": "Maul", "damage_str": "Str+d10", "ap": 2, "trait_type": "Melee",
     "range": "", "reach": 0, "weight": 10, "cost": "400", "notes": "AP 2, Two hands"},
    {"name": "Flail", "damage_str": "Str+d6", "ap": 0, "trait_type": "Melee",
     "range": "", "reach": 0, "weight": 3, "cost": "200", "notes": "Ignores Shield bonus"},
    {"name": "Warhammer", "damage_str": "Str+d6", "ap": 1, "trait_type": "Melee",
     "range": "", "reach": 0, "weight": 3, "cost": "200", "notes": "AP 1"},
    {"name": "Spear", "damage_str": "Str+d6", "ap": 0, "trait_type": "Melee",
     "range": "3/6/12", "reach": 1, "weight": 3, "cost": "100", "notes": "Reach 1, Parry +1 (two hands), can be thrown"},
    {"name": "Pike", "damage_str": "Str+d8", "ap": 0, "trait_type": "Melee",
     "range": "", "reach": 2, "weight": 8, "cost": "200", "notes": "Reach 2, Two hands"},
    {"name": "Halberd", "damage_str": "Str+d8", "ap": 0, "trait_type": "Melee",
     "range": "", "reach": 1, "weight": 6, "cost": "250", "notes": "Reach 1, Two hands"},
    {"name": "Staff", "damage_str": "Str+d4", "ap": 0, "trait_type": "Melee",
     "range": "", "reach": 1, "weight": 4, "cost": "10", "notes": "Reach 1, Parry +1, Two hands"},
    {"name": "Lance", "damage_str": "Str+d8", "ap": 2, "trait_type": "Melee",
     "range": "", "reach": 2, "weight": 6, "cost": "300", "notes": "AP 2, Reach 2, requires mount"},
    {"name": "Club", "damage_str": "Str+d4", "ap": 0, "trait_type": "Melee",
     "range": "", "reach": 0, "weight": 2, "cost": "5", "notes": ""},
    # Ranged Weapons
    {"name": "Bow", "damage_str": "2d6", "ap": 0, "trait_type": "Ranged",
     "range": "12/24/48", "reach": 0, "weight": 2, "cost": "250", "notes": ""},
    {"name": "Longbow", "damage_str": "2d6", "ap": 1, "trait_type": "Ranged",
     "range": "15/30/60", "reach": 0, "weight": 3, "cost": "300", "notes": "AP 1"},
    {"name": "Crossbow", "damage_str": "2d6", "ap": 2, "trait_type": "Ranged",
     "range": "15/30/60", "reach": 0, "weight": 5, "cost": "250", "notes": "AP 2, Reload 1"},
    {"name": "Sling", "damage_str": "Str+d4", "ap": 0, "trait_type": "Ranged",
     "range": "4/8/16", "reach": 0, "weight": 0.5, "cost": "10", "notes": ""},
    {"name": "Net (Weighted)", "damage_str": "-", "ap": 0, "trait_type": "Thrown",
     "range": "3/6/12", "reach": 0, "weight": 4, "cost": "50", "notes": "Entangle, -2 Pace, Bound on Raise"},
]

ARMOR = [
    {"name": "Leather", "protection": 2, "area_protected": "Torso, arms, legs",
     "min_strength": "d6", "weight": 10, "cost": "50", "notes": ""},
    {"name": "Chain Mail", "protection": 3, "area_protected": "Torso, arms, legs",
     "min_strength": "d8", "weight": 25, "cost": "300", "notes": ""},
    {"name": "Plate Mail", "protection": 4, "area_protected": "Torso, arms, legs",
     "min_strength": "d10", "weight": 35, "cost": "500", "notes": ""},
    {"name": "Pot Helm", "protection": 3, "area_protected": "Head",
     "min_strength": "", "weight": 3, "cost": "75", "notes": "50% vs head shot"},
    {"name": "Full Helm", "protection": 3, "area_protected": "Head",
     "min_strength": "", "weight": 4, "cost": "150", "notes": ""},
    {"name": "Small Shield", "protection": 0, "area_protected": "Shield",
     "min_strength": "", "weight": 4, "cost": "25", "notes": "Parry +1"},
    {"name": "Medium Shield", "protection": 2, "area_protected": "Shield",
     "min_strength": "", "weight": 8, "cost": "50", "notes": "Parry +2, +2 Armor vs ranged"},
    {"name": "Large Shield", "protection": 2, "area_protected": "Shield",
     "min_strength": "", "weight": 12, "cost": "75", "notes": "Parry +3, +2 Armor vs ranged, -1 to attack"},
]

GEAR = [
    {"name": "Backpack", "weight": 2, "cost": "50", "notes": ""},
    {"name": "Bedroll", "weight": 4, "cost": "25", "notes": ""},
    {"name": "Candle (10)", "weight": 1, "cost": "5", "notes": ""},
    {"name": "Crowbar", "weight": 2, "cost": "10", "notes": ""},
    {"name": "Flint & Steel", "weight": 0.5, "cost": "3", "notes": ""},
    {"name": "Grappling Hook", "weight": 2, "cost": "100", "notes": ""},
    {"name": "Hammer", "weight": 1, "cost": "10", "notes": ""},
    {"name": "Lantern", "weight": 2, "cost": "25", "notes": ""},
    {"name": "Lockpicks", "weight": 0.5, "cost": "200", "notes": ""},
    {"name": "Manacles", "weight": 1, "cost": "15", "notes": ""},
    {"name": "Oil (1 pint)", "weight": 1, "cost": "2", "notes": ""},
    {"name": "Quiver (20 arrows)", "weight": 2, "cost": "25", "notes": ""},
    {"name": "Rope (50')", "weight": 7, "cost": "10", "notes": ""},
    {"name": "Shovel", "weight": 3, "cost": "5", "notes": ""},
    {"name": "Spyglass", "weight": 1, "cost": "500", "notes": ""},
    {"name": "Torch (6)", "weight": 3, "cost": "5", "notes": ""},
    {"name": "Waterskin", "weight": 1, "cost": "5", "notes": ""},
    {"name": "Whetstone", "weight": 0.5, "cost": "5", "notes": ""},
    {"name": "Fine Clothing", "weight": 2, "cost": "200", "notes": ""},
    {"name": "Normal Clothing", "weight": 2, "cost": "20", "notes": ""},
    {"name": "Winter Clothing", "weight": 4, "cost": "50", "notes": ""},
    {"name": "Rations (1 week)", "weight": 5, "cost": "10", "notes": ""},
    {"name": "Healers Kit", "weight": 2, "cost": "25", "notes": "+1 Healing, 5 uses"},
]
